### ISSUE TITLE
log path maybe incorrect

### ISSUE THREAD

**Issue by vimagick** [houselabs/docker-strongswan-buildconf#1]
Great job 👍 

I notice that `log` directory is not at same level as `strongswan.d`.
## https://github.com/houselabs/docker-strongswan-buildconf/blob/master/src/init.sh

```
...
mkdir -p $OUT/strongswan/log/
touch $OUT/strongswan/log/charon.log
...
sed -i "s#VPN_DNS#${VPN_DNS}#g" $OUT/strongswan.d/charon.conf
...
```
## https://github.com/houselabs/docker-strongswan

```
...
docker run -i -v /data/strongswan:/data \
...
docker run -d --name=strongswan \
...
  -v /data/strongswan/strongswan.d:/etc/strongswan.d \
  -v /data/strongswan/log/charon.log:/var/log/charon.log \
...
```

**Comment by we11adam** [comment]
This issue is addressed in https://github.com/houselabs/docker-strongswan/commit/f02b193e51e58893750b49df49157e4be6670a0d

Please try it out and provide further feedback.

Thanks.

**Comment by vimagick** [comment]
👍
